### ISSUE TITLE
Equations implemented in modelDB provided code different from eqs used to generate figures in paper

### ISSUE THREAD

**Issue by JustasB** [OpenSourceBrain/PospischilEtAl2008#16]
@pgleeson @scrook

Team, I used Sharon's suggestion to re-implement the RS cell model in XPP using the equations provided in the paper. When I do that, I get a closer match of sub-threshold behavior to the published figure 1C than when I run the original provided NEURON code.

Here is XPP, paper figure 1C, and NEURON_ORIG side by side:

![side by side](https://cloud.githubusercontent.com/assets/10732358/9365342/e35bb69a-4665-11e5-9f7d-0aedd614bdd1.jpg)

Here is NEURON_ORIG superimposed with Paper Figure 1C (**Thick line** is NEURON, thin is paper):
![neuron_orig vs figure](https://cloud.githubusercontent.com/assets/10732358/9365426/5e5fbfa8-4666-11e5-94a0-71f0562d50ee.jpg)

And XPP with paper provided equations vs Paper Figure:
![xpp vs figure](https://cloud.githubusercontent.com/assets/10732358/9365425/5e5b7c36-4666-11e5-8b0b-574b09579836.jpg)

This suggests that the NEURON code provided in modelDB implements equations slightly different than the ones reported and used to generate figures in the paper.

Looking at the NEURON_ORIG mod files, it looks like the alpha and beta variables for the Na & K channels may be different than the ones in the paper.

**Comment by pgleeson** [comment]
Sigh...

Try to see if you can get some mods that more closely match the paper. Also please add the XPP to the repo. 

Fri is the pencils down date, so please make sure you add some info on this and the project contents of the repo in general in READMEs. Thanks.

**Comment by JustasB** [comment]
Ok, adding a DC current, changing the Vtraub parameter, and using a different input current, gets a closer match. These can be seen under the XPP folder.
