### ISSUE TITLE
Get RS cell to match original NEURON code

### ISSUE THREAD

**Issue by pgleeson** [OpenSourceBrain/PospischilEtAl2008#3]
Example [RS cell](https://github.com/OpenSourceBrain/PospischilEtAl2008/blob/master/NeuroML2/RS_ModelDB.cell.nml) model [converted to NeuroML2/LEMS](https://github.com/OpenSourceBrain/PospischilEtAl2008/blob/master/NeuroML2/LEMS_PospischilEtAl2008.xml) should match [original version from ModelDB](http://senselab.med.yale.edu/ModelDB/ShowModel.cshtml?model=123623&file=PospischilEtAl2008rundemo.hoc).

Close but not a good match yet...

![selection_219](https://cloud.githubusercontent.com/assets/1556687/7990478/33ce5ef6-0ae9-11e5-80b1-313b63fd18d5.png)

Top: jnml running model. Middle: jnml -neuron. Bottom: original NEURON model.

**Comment by JustasB** [comment]
The issue is the K im channel steady state gate being initialized to 0 in the original model. When it's initialized to the steady state value, the models match. This means that:
1. The original contains a mistake
2. A new component needs to be created that allows setting the initial gate value to 0

**Comment by pgleeson** [comment]
Good match now, as illustrated by:
https://github.com/OpenSourceBrain/PospischilEtAl2008/blob/master/NEURON_MODIFIED/.test.RS.spikes.omt
https://github.com/OpenSourceBrain/PospischilEtAl2008/blob/master/NeuroML2/cells/RS/.test.RS.spikes.neuron.omt
https://github.com/OpenSourceBrain/PospischilEtAl2008/blob/master/NeuroML2/cells/RS/.test.RS.spikes.LEMS.omt
