### ISSUE TITLE
Unexplained calcium pool equation in cadecay_destexhe.mod

### ISSUE THREAD

**Issue by JustasB** [OpenSourceBrain/PospischilEtAl2008#9]
In original version, the calcium concentration is computed as follows:

```
DERIVATIVE state { 

    drive_channel =  - (10000) * ica / (2 * FARADAY * depth)

    if (drive_channel <= 0.) { drive_channel = 0. } : cannot pump inward

    cai' = drive_channel + (cainf-cai)/taur
}
```

In the converted version, I use [decayingPoolConcentrationModel](https://neuroml.org/NeuroML2CoreTypes/Cells.html#decayingPoolConcentrationModel), which has slightly different equations for concentration:

```

Derived Variables

    innerRadius = effectiveRadius - shellThickness    
    effectiveRadius = LENGTH_SCALE * sqrt(surfaceArea/(AREA_SCALE * (4 * 3.14159)))    
    shellVolume = (4 * (effectiveRadius * effectiveRadius * effectiveRadius) * 3.14159 / 3) - (4 * (innerRadius * innerRadius * innerRadius) * 3.14159 / 3)    

Time Derivatives

    d concentration /dt = iCa / (2 * Faraday * shellVolume) - ((concentration - restingConc) / decayConstant)
```

This may be contributing to small differences between original and converted versions.

**Comment by pgleeson** [comment]
Is this still relevant, given you're using the custom component type now?

**Comment by JustasB** [comment]
Ok, this is addressed with the custom component now.
